/*
 * To see the assembly code generated by compiler
 */

void multstore(long, long, long *);
long mult2(long, long);

void multstore(long x, long y, long *dest) {
	long t = mult2(x, y);
	*dest = t;
}

long mult2(long x, long y) {
	return x * y;
}
